package tugasperpus;
import java.io.File;
import java.sql.*;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import static tugasperpus.koneksi.koneksiDb;

import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Locale;


import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import static tugasperpus.koneksi.koneksiDb;
/**
 *
 * @author firzi
 */
public final class Anggotaperpus extends javax.swing.JFrame {
    Connection koneksi = null;
    private DefaultTableModel tabmode;
    
    /**
     * Creates new form Anggotaperpus
     */
    public Anggotaperpus() {
        initComponents();
        setLocationRelativeTo(null);
        koneksi = koneksiDb();
        dataanggota();
      
       Locale locale = new Locale ("id","ID");
       Locale.setDefault(locale);
        JComboBox<Object> comboBox = new JComboBox<>();
        comboBox.addItem("Nis");
        comboBox.addItem("Nama");
        
    }

    protected void aktif(){
        tnis.setEnabled(true);
        tnama.setEnabled(true);
        talm.setEnabled(true);
        tnis.requestFocus();
    }
    
    protected void kosong () {
        tnis.setText("");
        tnama.setText("");
        ckelas.setSelectedIndex(0);
        rjk1.setSelected(true);
        talm.setText("");
        cagama.setSelectedIndex(0);
        tnotlpn.setText("");
        tcarianggota.setText("");
        
    }
    
    protected void dataanggota () {
    Object[] Baris ={"Nis", "Nama", "Kelas", "JK", "Alamat", "Agama", "NoTlpn"};
    tabmode = new DefaultTableModel(null, Baris);
    Tableanggota.setModel(tabmode);
    String sql = "SELECT * FROM db_anggota";
    try {
        java.sql.Statement stat = koneksi.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
           String a = hasil.getString("Nis");
           String b = hasil.getString("Nama");
           String c = hasil.getString("Kelas");
           String d = hasil.getString("Jeniskelamin");
           String e = hasil.getString("Alamat");
           String f = hasil.getString("Agama");
           String g = hasil.getString("Notelpon");
           
           String[] data={a,b,c,d,e,f,g};
           tabmode.addRow(data);
      }
    } catch (SQLException e) {
        System.out.println("Error Data:" + e.getMessage());
    }
}  
    
    private Connection koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_login","root","");
        return koneksi;
        
    }catch (Exception e){
        System.out.println("Koneksi Gagal:" + e.getMessage());
        return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        tnis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        talm = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        rjk1 = new javax.swing.JRadioButton();
        rjk2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tnotlpn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cagama = new javax.swing.JComboBox<>();
        cpencariananggota = new javax.swing.JComboBox<>();
        tcarianggota = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnclear = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tableanggota = new javax.swing.JTable();
        btncari = new javax.swing.JButton();
        ckelas = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuback = new javax.swing.JMenu();
        jback = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mdatabuku = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mdataanggota = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mdatapegawai = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mdatapeminjaman = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mdatapengembalian = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mdenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/Administrasii_Perpus.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("NIS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(tnis, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 131, 220, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 39, -1));
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 196, 220, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Kelas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 258, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("JK");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 318, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Alamat");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 371, -1, -1));

        talm.setColumns(20);
        talm.setRows(5);
        jScrollPane1.setViewportView(talm);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 371, 290, 171));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("No. Telpon");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 195, 81, -1));

        rjk1.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        rjk1.setText("Laki - laki");
        getContentPane().add(rjk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 318, 82, -1));

        rjk2.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        rjk2.setText("Perempuan");
        rjk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjk2ActionPerformed(evt);
            }
        });
        getContentPane().add(rjk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 318, 91, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRASI PERPUSTAKAAN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 280, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SDIT Hidayatullah");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jl. Cilangkap Baru No.99, RT.1/RW.1, Cilangkap, Kec. Cipayung, Kota Jakarta Timur");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 61, -1, 14));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Instagram : tkit_cahayabintang ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 0, 740, 110));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_SD (1).png"))); // NOI18N
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 110, 110));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("DATA ANGGOTA");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 150, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 0, 340, 113));
        getContentPane().add(tnotlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 196, 235, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Agama");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 131, -1, -1));

        cagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "" }));
        getContentPane().add(cagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 132, 96, -1));

        cpencariananggota.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        cpencariananggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIS", "Nama" }));
        getContentPane().add(cpencariananggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 249, 82, -1));
        getContentPane().add(tcarianggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 251, 235, -1));

        jPanel4.setBackground(new java.awt.Color(102, 255, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclear.setBackground(new java.awt.Color(255, 255, 51));
        btnclear.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refreshlogo.png"))); // NOI18N
        btnclear.setText("REFRESH");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel4.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, -1, -1));

        btnexit.setBackground(new java.awt.Color(255, 255, 51));
        btnexit.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitlogo.png"))); // NOI18N
        btnexit.setText("KELUAR");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel4.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, -1, -1));

        btnprint.setBackground(new java.awt.Color(255, 255, 51));
        btnprint.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printerlogo.png"))); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel4.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 111, -1));

        btnsave.setBackground(new java.awt.Color(255, 255, 0));
        btnsave.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simpanlogo.png"))); // NOI18N
        btnsave.setText("SIMPAN");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        btndelete.setBackground(new java.awt.Color(255, 255, 51));
        btndelete.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hapuslogo.png"))); // NOI18N
        btndelete.setText("HAPUS");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 110, -1));

        btnedit.setBackground(new java.awt.Color(255, 255, 51));
        btnedit.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editlogo.png"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel4.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 110, -1));

        Tableanggota.setBackground(new java.awt.Color(204, 204, 204));
        Tableanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama ", "Kelas", "Jeniskelamin", "Alamat", "Agama", "Notelpon"
            }
        ));
        Tableanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableanggotaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tableanggota);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 620, 230));

        btncari.setBackground(new java.awt.Color(255, 255, 51));
        btncari.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btncari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel4.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, -1, -1));

        ckelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 A", "1 B", "1 C", "2 A", "2 B", "2 C", "3 A", "3 B", "3 C", "4 A", "4 B", "4 C", "5 A", "5 B", "5 C", "6 A", "6 B", "6 C" }));
        jPanel4.add(ckelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 110, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1070, 480));

        jmenuback.setText("Menu Utama");
        jmenuback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenubackActionPerformed(evt);
            }
        });

        jback.setText("Menu Utama");
        jback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackActionPerformed(evt);
            }
        });
        jmenuback.add(jback);

        jMenuBar1.add(jmenuback);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Buku");

        mdatabuku.setText("Data Buku");
        mdatabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatabukuActionPerformed(evt);
            }
        });
        jMenu3.add(mdatabuku);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Anggota");

        mdataanggota.setText("Data Anggota");
        mdataanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdataanggotaActionPerformed(evt);
            }
        });
        jMenu4.add(mdataanggota);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Pustakawan");

        mdatapegawai.setText("Data Pustakawan");
        mdatapegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatapegawaiActionPerformed(evt);
            }
        });
        jMenu5.add(mdatapegawai);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Peminjaman");

        mdatapeminjaman.setText("Data Peminjaman");
        mdatapeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatapeminjamanActionPerformed(evt);
            }
        });
        jMenu6.add(mdatapeminjaman);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Pengembalian");

        mdatapengembalian.setText("Data Pengembalian");
        mdatapengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatapengembalianActionPerformed(evt);
            }
        });
        jMenu7.add(mdatapengembalian);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Denda");

        mdenda.setText("Denda");
        mdenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdendaActionPerformed(evt);
            }
        });
        jMenu8.add(mdenda);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO db_anggota (Nis, Nama, Kelas, Jeniskelamin, Alamat, Agama, Notelpon) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement ps = koneksi.prepareStatement(sql);
            ps.setString(1, tnis.getText());
            ps.setString(2, tnama.getText());
            ps.setString(3, ckelas.getSelectedItem().toString());
            
            String jkel="";
            if(rjk1.isSelected()) jkel="Laki-laki";
            else jkel="Perempuan";
            ps.setString(4, jkel);
            
            ps.setString(5, talm.getText());
            ps.setString(6, cagama.getSelectedItem().toString());
            ps.setString(7, tnotlpn.getText());
            
            ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di Simpan");
                kosong();
                tnis.requestFocus();
                dataanggota();
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error:" + e.getMessage());
            }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        int rowIndex = Tableanggota.getSelectedRow();
       
       if (rowIndex == -1){
           JOptionPane.showMessageDialog(null, "Pilih data yang akan di ubah");
          return;
       } 
        
        try {
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_login","root","");
           String nis = tnis.getText();
           String nama = tnama.getText();
           String kelas = (String) ckelas.getSelectedItem();
           String jeniskelamin = rjk1.isSelected() ? "Laki-laki" : "Perempuan";
           String alamat = talm.getText();
           String agama = (String) cagama.getSelectedItem();
           String notelpon = tnotlpn.getText();
           
           
         
           String sql = "UPDATE db_anggota set Nis=?, Nama=?, Kelas=?, Jeniskelamin=?, Alamat=?, Agama=?, Notelpon=?  WHERE Nis =?";
           PreparedStatement stat = koneksi.prepareStatement(sql);
           stat.setString(1, nis);
           stat.setString(2, nama);
           stat.setString(3, kelas);
           stat.setString(4, jeniskelamin);
           stat.setString(5, alamat);
           stat.setString(6, agama);
           stat.setString(7, notelpon);
           stat.setString(8, tabmode.getValueAt(rowIndex, 0).toString());
            
           
           int result = stat.executeUpdate();
           
            if(result == 1){
                
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                kosong();
                tnis.requestFocus();
                dataanggota();
             } else {
                JOptionPane.showMessageDialog(null, "Gagal Mengubah");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
       }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        kosong();
        dataanggota();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         int[] selectedRows = Tableanggota.getSelectedRows();

    if (selectedRows.length == 0) {
        JOptionPane.showMessageDialog(null, "Pilih Data yang akan di Hapus");
        return;
    }

    // Buat koneksi dan statement di luar loop
    try {
        String sql = "DELETE FROM db_anggota WHERE Nis=?";
        PreparedStatement stat = koneksi.prepareStatement(sql);

        // Loop untuk menghapus semua data yang dipilih
        for (int i = 0; i < selectedRows.length; i++) {
            int rowIndex = selectedRows[i];
            String nis = tabmode.getValueAt(rowIndex, 0).toString();
            stat.setString(1, nis);

            // Eksekusi perintah untuk menghapus data
            stat.executeUpdate();
        }

        // Setelah semua baris dihapus, tampilkan pesan sekali saja
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

        // Perbarui tampilan tabel setelah penghapusan
        dataanggota();
        kosong();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void mdatabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatabukuActionPerformed
        // TODO add your handling code here:
         dispose();
        
        Bukuperpus Bukuperpus= new Bukuperpus();
        Bukuperpus.setVisible(true);
    }//GEN-LAST:event_mdatabukuActionPerformed

    private void jmenubackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenubackActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jmenubackActionPerformed

    private void jbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackActionPerformed
        // TODO add your handling code here:
         dispose();

        MenuUtama MenuUtama= new MenuUtama();
        MenuUtama.setVisible(true);
    }//GEN-LAST:event_jbackActionPerformed

    private void TableanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableanggotaMouseClicked
        // TODO add your handling code here:
        int bar = Tableanggota.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();

        tnis.setText(a);
        tnama.setText(b);
        ckelas.setSelectedItem(c);

        if(d.equals("Laki-laki")) {rjk1.setSelected(true); rjk2.setSelected(false);}
        else {rjk1.setSelected(false); rjk2.setSelected(true);}

        talm.setText(e);
        cagama.setSelectedItem(f);
        tnotlpn.setText(g);
    }//GEN-LAST:event_TableanggotaMouseClicked

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) cpencariananggota.getSelectedItem();
        String carianggota = tcarianggota.getText();

        Object[] Baris = {"Nis", "Nama", "Kelas", "Jeniskelamin", "Alamat", "Agama", "Notelpon"};
        tabmode = new DefaultTableModel(null, Baris);
        Tableanggota.setModel(tabmode);

        String sql = "SELECT * FROM db_anggota WHERE Nis LIKE ? OR Nama LIKE ?";

        try {
            PreparedStatement stat = koneksi.prepareStatement(sql);
            stat.setString(1, "%" + carianggota + "%");
            stat.setString(2, "%" + carianggota + "%");

            ResultSet hasil = stat.executeQuery();
            while(hasil.next()){
                String a = hasil.getString("Nis");
                String b = hasil.getString("Nama");
                String c = hasil.getString("Kelas");
                String d = hasil.getString("Jeniskelamin");
                String e = hasil.getString("Alamat");
                String f = hasil.getString("Agama");
                String g = hasil.getString("Notelpon");

                String[] data={a, b, c, d, e, f, g};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erorr : " + e.getMessage());
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void rjk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rjk2ActionPerformed

    private void mdataanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdataanggotaActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Anggotaperpus Anggotaperpus= new Anggotaperpus();
        Anggotaperpus.setVisible(true);
    }//GEN-LAST:event_mdataanggotaActionPerformed

    private void mdatapegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatapegawaiActionPerformed
        // TODO add your handling code here:
          dispose();
        
        Pegawaiperpus Pegawaiperpus= new Pegawaiperpus();
        Pegawaiperpus.setVisible(true);
    }//GEN-LAST:event_mdatapegawaiActionPerformed

    private void mdatapeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatapeminjamanActionPerformed
        // TODO add your handling code here:
         dispose();
        
        Peminjamanperpus Peminjamanperpus= new Peminjamanperpus();
        Peminjamanperpus.setVisible(true);
    }//GEN-LAST:event_mdatapeminjamanActionPerformed

    private void mdatapengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatapengembalianActionPerformed
        // TODO add your handling code here:
         dispose();
        
        Pengembalianperpus Pengembalianperpus= new Pengembalianperpus();
        Pengembalianperpus.setVisible(true);
    }//GEN-LAST:event_mdatapengembalianActionPerformed

    private void mdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdendaActionPerformed
        // TODO add your handling code here:
         dispose();
        
        Dendaperpus Dendaperpus= new Dendaperpus();
        Dendaperpus.setVisible(true);
    }//GEN-LAST:event_mdendaActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        try {
        String namaFile = "src/Laporan/LaporanAnggota.jasper";
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_login","root",""); 
        HashMap<String, Object> parameter = new HashMap<>();
        File report_file = new File(namaFile);
        if (report_file.exists()) {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } else {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan.");
        }
    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
     }    
    }//GEN-LAST:event_btnprintActionPerformed

       
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anggotaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anggotaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anggotaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anggotaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anggotaperpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tableanggota;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cagama;
    private javax.swing.JComboBox<String> ckelas;
    private javax.swing.JComboBox<String> cpencariananggota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jback;
    private javax.swing.JMenu jmenuback;
    private javax.swing.JMenuItem mdataanggota;
    private javax.swing.JMenuItem mdatabuku;
    private javax.swing.JMenuItem mdatapegawai;
    private javax.swing.JMenuItem mdatapeminjaman;
    private javax.swing.JMenuItem mdatapengembalian;
    private javax.swing.JMenuItem mdenda;
    private javax.swing.JRadioButton rjk1;
    private javax.swing.JRadioButton rjk2;
    private javax.swing.JTextArea talm;
    private javax.swing.JTextField tcarianggota;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnis;
    private javax.swing.JTextField tnotlpn;
    // End of variables declaration//GEN-END:variables

    private void String(int i, String jkel) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
