/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tugasperpus;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static tugasperpus.koneksi.koneksiDb;
 
/**
 *
 * @author firzi
 */
public final class Dendaperpus extends javax.swing.JFrame {
    Connection koneksi = null;
    private DefaultTableModel tabmode;
    /** Creates new form Dendaperpus */
    
    public Dendaperpus() {
        initComponents();
        setLocationRelativeTo(null);
        koneksi = koneksiDb();
        datadenda1 ();
        
        JComboBox<Object> comboBox = new JComboBox<>();
        comboBox.addItem("Nis");
        comboBox.addItem("Nama");
        comboBox.addItem("Kodebuku");
    }


protected void datadenda1() {
    Object[] Baris = {"Nis", "Nama", "Nip", "Pegawai", "Kode_buku", "Judul_buku", "Tglpengembalian", "Status", "Jumlahmeminjam"};
    tabmode = new DefaultTableModel(null, Baris);
    Tablepengembalian.setModel(tabmode); // Tabel di form pengembalian

    String sql = "SELECT * FROM db_pengembalian"; // Ambil data dari tabel peminjaman
    try {
        Statement stat = koneksi.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            String nis = hasil.getString("Nis");
            String nama = hasil.getString("Nama");
            String nip = hasil.getString("Nip");
            String pegawai = hasil.getString("Pegawai");
            String kodeBuku = hasil.getString("Kode_buku");
            String judulBuku = hasil.getString("Judul_buku");
            String tglPengembalian = hasil.getString("Tglpengembalian");
            String status = hasil.getString("Status");
            String jumlahMeminjam = hasil.getString("Jumlahmeminjam");

       
            String[] data = {nis, nama, nip, pegawai, kodeBuku, judulBuku, tglPengembalian, status, jumlahMeminjam};
            tabmode.addRow(data);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error Data: " + e.getMessage());
    }
}

protected void loadDatadenda4() {
    Object[] Baris = {"Nis", "Nama", "Nip", "Pegawai", "Kode_buku", "Judul_buku",  "Tglpengembalian", "Status", "Jumlahmeminjam"};
    tabmode = new DefaultTableModel(null, Baris);
    Tablepengembalian.setModel(tabmode);

    
    String sql = "SELECT * FROM db_pengembalian"; 

    try {
        Statement stat = koneksiDb().createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()) {
            String nis = hasil.getString("Nis");
            String nama = hasil.getString("Nama");
            String nip = hasil.getString("Nip");
            String pegawai = hasil.getString("Pegawai");
            String kodeBuku = hasil.getString("Kode_buku");
            String judulBuku = hasil.getString("Judul_buku");
            String tglPengembalian = hasil.getString("Tglpengembalian");
            String status = hasil.getString("Status"); // Ambil status
            String jumlahMeminjam = hasil.getString("Jumlahmeminjam");

            // Tambahkan data ke tabel
            String[] data = {nis, nama, nip, pegawai, kodeBuku, judulBuku, tglPengembalian, status, jumlahMeminjam};
            tabmode.addRow(data); // Tambahkan data ke tabel
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error Data: " + e.getMessage());
    }
}
  private Connection koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_login","root","");
        return koneksi;
        
    }catch (Exception e){
        System.out.println("Koneksi Gagal:" + e.getMessage());
        return null;
    }
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnhitung = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ckondisi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cminjam1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tdenda2 = new javax.swing.JTextField();
        btnhitung2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dtelat2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        ckondisi2 = new javax.swing.JComboBox<>();
        cminjam2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tdenda3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnhitung3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        dtelat = new com.toedter.calendar.JDateChooser();
        tdenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ckategori2 = new javax.swing.JComboBox<>();
        tcari2 = new javax.swing.JTextField();
        btncari2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablepengembalian = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuutama = new javax.swing.JMenu();
        jmenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenubuku = new javax.swing.JMenu();
        jdatabuku = new javax.swing.JMenuItem();
        jmenuanggota = new javax.swing.JMenu();
        jdataanggota = new javax.swing.JMenuItem();
        jmenupegawai = new javax.swing.JMenu();
        jdatapegawai = new javax.swing.JMenuItem();
        jmenupeminjaman = new javax.swing.JMenu();
        jdatapeminjaman = new javax.swing.JMenuItem();
        jmenupengembalian = new javax.swing.JMenu();
        jdatapengembalian = new javax.swing.JMenuItem();
        jmenudenda = new javax.swing.JMenu();
        jdenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/Administrasii_Perpus.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_SD (1).png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 130, 110));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("DENDA");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 0, 320, 110));

        jPanel6.setBackground(new java.awt.Color(102, 255, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhitung.setBackground(new java.awt.Color(255, 255, 51));
        btnhitung.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        jPanel6.add(btnhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        btnrefresh.setBackground(new java.awt.Color(255, 153, 51));
        btnrefresh.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refreshlogo.png"))); // NOI18N
        btnrefresh.setText("REFRESH");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel6.add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        btnexit.setBackground(new java.awt.Color(255, 153, 51));
        btnexit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitlogo.png"))); // NOI18N
        btnexit.setText("KELUAR");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel6.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText("Kondisi Buku");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        ckondisi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ckondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Baik", "Kotor" }));
        jPanel6.add(ckondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 102, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Jumlah Kembali");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        cminjam1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jPanel6.add(cminjam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 50, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Denda");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));
        jPanel6.add(tdenda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 150, -1));

        btnhitung2.setBackground(new java.awt.Color(255, 255, 51));
        btnhitung2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhitung2.setText("Hitung");
        btnhitung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitung2ActionPerformed(evt);
            }
        });
        jPanel6.add(btnhitung2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Tgl Keterlambatan");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));
        jPanel6.add(dtelat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 163, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Kondisi Buku");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        ckondisi2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ckondisi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rusak", "Kotor" }));
        jPanel6.add(ckondisi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 70, -1));

        cminjam2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cminjam2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jPanel6.add(cminjam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 50, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("Jumlah Kembali");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));
        jPanel6.add(tdenda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 150, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("Denda");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        btnhitung3.setBackground(new java.awt.Color(255, 255, 51));
        btnhitung3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnhitung3.setText("Hitung");
        btnhitung3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitung3ActionPerformed(evt);
            }
        });
        jPanel6.add(btnhitung3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setText("Tgl Keterlambatan");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 107, -1));
        jPanel6.add(dtelat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 155, -1));

        tdenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdendaActionPerformed(evt);
            }
        });
        jPanel6.add(tdenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 140, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Denda");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 44, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 325, 1079, 190));

        jPanel1.setBackground(new java.awt.Color(102, 255, 0));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DATA PENGEMBALIAN");

        ckategori2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ckategori2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nis", "Nama", "Kodebuku" }));
        ckategori2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckategori2ActionPerformed(evt);
            }
        });

        tcari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcari2ActionPerformed(evt);
            }
        });

        btncari2.setBackground(new java.awt.Color(255, 255, 51));
        btncari2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btncari2.setText("CARI");
        btncari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncari2ActionPerformed(evt);
            }
        });

        Tablepengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nis", "Nama", "Nip", "Pegawai", "Kodebuku", "Judulbuku", "Tglpengembalian", "Status", "Jumlahmeminjam"
            }
        ));
        Tablepengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablepengembalianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablepengembalian);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckategori2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btncari2))
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckategori2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tcari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncari2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 220));

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrasi Perpustakaan ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 309, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SDIT Hidayatullah ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Jl. Cilangkap Baru No.99, RT.1/RW.1, Cilangkap, Kec. Cipayung, Kota Jakarta Timur ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 580, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Instagram : tkit_cahayabintang ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 190, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 110));

        jmenuutama.setText("Menu Utama");
        jmenuutama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuutamaActionPerformed(evt);
            }
        });

        jmenu.setText("Menu Utama");
        jmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuActionPerformed(evt);
            }
        });
        jmenuutama.add(jmenu);

        jMenuBar1.add(jmenuutama);
        jMenuBar1.add(jMenu2);

        jmenubuku.setText("Buku");
        jmenubuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenubukuActionPerformed(evt);
            }
        });

        jdatabuku.setText("Data Buku");
        jdatabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdatabukuActionPerformed(evt);
            }
        });
        jmenubuku.add(jdatabuku);

        jMenuBar1.add(jmenubuku);

        jmenuanggota.setText("Anggota");
        jmenuanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuanggotaActionPerformed(evt);
            }
        });

        jdataanggota.setText("Data Anggota");
        jdataanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdataanggotaActionPerformed(evt);
            }
        });
        jmenuanggota.add(jdataanggota);

        jMenuBar1.add(jmenuanggota);

        jmenupegawai.setText("Pegawai");
        jmenupegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenupegawaiActionPerformed(evt);
            }
        });

        jdatapegawai.setText("Data Pegawai");
        jdatapegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdatapegawaiActionPerformed(evt);
            }
        });
        jmenupegawai.add(jdatapegawai);

        jMenuBar1.add(jmenupegawai);

        jmenupeminjaman.setText("Peminjaman");
        jmenupeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenupeminjamanActionPerformed(evt);
            }
        });

        jdatapeminjaman.setText("Data Peminjaman");
        jdatapeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdatapeminjamanActionPerformed(evt);
            }
        });
        jmenupeminjaman.add(jdatapeminjaman);

        jMenuBar1.add(jmenupeminjaman);

        jmenupengembalian.setText("Pengembalian");
        jmenupengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenupengembalianActionPerformed(evt);
            }
        });

        jdatapengembalian.setText("Data Pengembalian");
        jdatapengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdatapengembalianActionPerformed(evt);
            }
        });
        jmenupengembalian.add(jdatapengembalian);

        jMenuBar1.add(jmenupengembalian);

        jmenudenda.setText("Denda");
        jmenudenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenudendaActionPerformed(evt);
            }
        });

        jdenda.setText("Denda");
        jdenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdendaActionPerformed(evt);
            }
        });
        jmenudenda.add(jdenda);

        jMenuBar1.add(jmenudenda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuutamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuutamaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jmenuutamaActionPerformed

    private void jmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuActionPerformed
        // TODO add your handling code here:
         dispose();

        MenuUtama MenuUtama= new MenuUtama();
        MenuUtama.setVisible(true);
    }//GEN-LAST:event_jmenuActionPerformed

    private void jdatabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdatabukuActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Bukuperpus Bukuperpus= new Bukuperpus();
        Bukuperpus.setVisible(true);
    }//GEN-LAST:event_jdatabukuActionPerformed

    private void jmenubukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenubukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenubukuActionPerformed

    private void jdataanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdataanggotaActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Anggotaperpus Anggotaperpus= new Anggotaperpus();
        Anggotaperpus.setVisible(true);
    }//GEN-LAST:event_jdataanggotaActionPerformed

    private void jmenuanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuanggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuanggotaActionPerformed

    private void jdatapegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdatapegawaiActionPerformed
        // TODO add your handling code here:
          dispose();
        
        Pegawaiperpus Pegawaiperpus= new Pegawaiperpus();
        Pegawaiperpus.setVisible(true);
    }//GEN-LAST:event_jdatapegawaiActionPerformed

    private void jmenupegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenupegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenupegawaiActionPerformed

    private void jdatapeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdatapeminjamanActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Peminjamanperpus Peminjamanperpus= new Peminjamanperpus();
        Peminjamanperpus.setVisible(true);
    }//GEN-LAST:event_jdatapeminjamanActionPerformed

    private void jmenupeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenupeminjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenupeminjamanActionPerformed

    private void jdatapengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdatapengembalianActionPerformed
        // TODO add your handling code here:
          dispose();
        
        Pengembalianperpus Pengembalianperpus= new Pengembalianperpus();
        Pengembalianperpus.setVisible(true);
    }//GEN-LAST:event_jdatapengembalianActionPerformed

    private void jmenupengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenupengembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenupengembalianActionPerformed

    private void jdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdendaActionPerformed
        // TODO add your handling code here:
          dispose();
        
        Dendaperpus Dendaperpus= new Dendaperpus();
        Dendaperpus.setVisible(true);
    }//GEN-LAST:event_jdendaActionPerformed

    private void jmenudendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenudendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenudendaActionPerformed

    private void TablepengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablepengembalianMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_TablepengembalianMouseClicked

    private void btncari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncari2ActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) ckategori2.getSelectedItem();
        String cari = tcari2.getText();

        Object[] Baris = {"Nis","Nama", "Nip", "Pegawai", "Kodebuku", "Judulbuku", "Tglpengembalian",  "Status", "Jumlahmeminjam"};
        tabmode = new DefaultTableModel(null, Baris);
        Tablepengembalian.setModel(tabmode);

        String sql = "SELECT * FROM db_pengembalian WHERE Nis LIKE ? OR Nama LIKE ? OR Kode_buku LIKE ?";

        try {
            PreparedStatement stat = koneksi.prepareStatement(sql);
            stat.setString(1, "%" + cari + "%");
            stat.setString(2, "%" + cari + "%");
            stat.setString(3, "%" + cari + "%");

            ResultSet hasil = stat.executeQuery();
            while(hasil.next()){
                String a = hasil.getString("Nis");
                String b = hasil.getString("Nama");
                String c = hasil.getString("Nip");
                String d = hasil.getString("Pegawai");
                String e = hasil.getString("Kode_buku");
                String f = hasil.getString("Judul_buku");
                String g = hasil.getString("Tglpengembalian");
                String h = hasil.getString("Status");
                String i = hasil.getString("Jumlahmeminjam");

                String[] data={a, b, c, d, e, f, g, h, i};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erorr : " + e.getMessage());
        }
    }//GEN-LAST:event_btncari2ActionPerformed

    private void ckategori2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckategori2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckategori2ActionPerformed

    private void tcari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcari2ActionPerformed

    private void btnhitung3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitung3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date tglPengembalianDate = null;
        Date tglKeterlambatanDate = null;

        try {

            String tglPengembalianStr = Tablepengembalian.getValueAt(Tablepengembalian.getSelectedRow(), 6).toString();
            tglPengembalianDate = sdf.parse(tglPengembalianStr); // Parsing string menjadi Date

            // Ambil tanggal keterlambatan dari JDateChooser
            if (dtelat2.getDate() != null) {
                tglKeterlambatanDate = dtelat2.getDate();
            } else {
                JOptionPane.showMessageDialog(null, "Silakan pilih Tanggal Keterlambatan.");
                return;
            }
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan dalam format tanggal.");
            return;
        }

        // Hitung perbedaan hari (keterlambatan)
        long diffInMillies = tglKeterlambatanDate.getTime() - tglPengembalianDate.getTime();
        long diffInDays = diffInMillies / (1000 * 60 * 60 * 24); // Konversi dari milidetik ke hari

        // Perhitungan denda keterlambatan
        int dendaKeterlambatan = 0;
        if (diffInDays > 0) {
            dendaKeterlambatan = (int) diffInDays * 2000; // Rp 2000 per hari keterlambatan
        }

        // Ambil kondisi buku dari ComboBox
        String kondisiBuku = ckondisi2.getSelectedItem().toString();
        int dendaKondisi = 0;

        // Ambil jumlah buku yang dipinjam dari tabel (asumsi kolom ke-9 adalah jumlah meminjam)
        int jumlahMeminjam = Integer.parseInt(Tablepengembalian.getValueAt(Tablepengembalian.getSelectedRow(), 8).toString());

        // Ambil jumlah buku yang rusak/kotor dari ComboBox (Anda perlu menambahkan ComboBox untuk memilih jumlah buku rusak/kotor)
        int jumlahRusakKotor = Integer.parseInt(cminjam2.getSelectedItem().toString());

        // Hitung denda berdasarkan kondisi buku dan jumlah buku yang rusak/kotor
        if (kondisiBuku.equals("Rusak")) {
            dendaKondisi = 5000 * jumlahRusakKotor;
        } else if (kondisiBuku.equals("Kotor")) {
            dendaKondisi = 7000 * jumlahRusakKotor;
        }

        // Validasi: pastikan jumlah buku rusak/kotor tidak melebihi jumlah buku yang dipinjam
        if (jumlahRusakKotor > jumlahMeminjam) {
            JOptionPane.showMessageDialog(null, "Jumlah buku rusak/kotor tidak boleh lebih dari jumlah yang dipinjam.");
            return;
        }

        // Hitung total denda (keterlambatan + kondisi buku)
        int totalDenda = dendaKeterlambatan + dendaKondisi;

        // Tampilkan hasil total denda ke text field
        tdenda3.setText(String.valueOf(totalDenda));
    }//GEN-LAST:event_btnhitung3ActionPerformed

    private void btnhitung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitung2ActionPerformed
        // TODO add your handling code here:
        try {
            // Pastikan pengguna telah memilih baris di tabel pengembalian
            int selectedRow = Tablepengembalian.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Pilih baris di tabel terlebih dahulu.");
                return;
            }

            // Ambil nilai jumlah meminjam dari kolom 'jumlahmeminjam' (misal indeks ke-8)
            int jumlahMeminjam;
            try {
                // Sesuaikan dengan indeks kolom yang benar (misal ke-8 untuk jumlah meminjam)
                jumlahMeminjam = Integer.parseInt(Tablepengembalian.getValueAt(selectedRow, 8).toString());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Nilai jumlah meminjam tidak valid.");
                return;
            }

            // Ambil nilai jumlah rusak/kotor dari combo box cminjam1
            int jumlahRusakKotor;
            try {
                jumlahRusakKotor = Integer.parseInt(cminjam1.getSelectedItem().toString());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Jumlah rusak/kotor tidak valid.");
                return;
            }

            // Cek apakah jumlah rusak/kotor tidak melebihi jumlah yang dipinjam
            if (jumlahRusakKotor > jumlahMeminjam) {
                JOptionPane.showMessageDialog(null, "Jumlah buku rusak/kotor tidak boleh melebihi jumlah yang dipinjam.");
                return;
            }

            // Ambil kondisi buku dari combo box ckondisi
            String kondisiBuku = (String) ckondisi.getSelectedItem();
            int dendaKondisi = 0;

            // Hitung denda berdasarkan kondisi buku
            if (kondisiBuku.equals("Rusak")) {
                dendaKondisi = 5000 * jumlahRusakKotor;
            } else if (kondisiBuku.equals("Kotor")) {
                dendaKondisi = 7000 * jumlahRusakKotor;
            } else {
                JOptionPane.showMessageDialog(null, "Kondisi buku tidak valid.");
                return;
            }

            // Tampilkan hasil denda kondisi buku di text field tdenda2
            tdenda2.setText(String.valueOf(dendaKondisi));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnhitung2ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        dtelat.setDate(null);
        dtelat2.setDate(null);
        ckondisi.setSelectedIndex(0);
        ckondisi2.setSelectedIndex(0);
        cminjam1.setSelectedIndex(0);
        cminjam2.setSelectedIndex(0);
        tdenda.setText("");
        tdenda2.setText("");
        tdenda3.setText("");

        Tablepengembalian.clearSelection(); // Menghilangkan pilihan di tabel (jika ada)

        JOptionPane.showMessageDialog(null, "Tabel Telah direset.");
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        Date TglpengembalianDate = null;
        Date tglKeterlambatanDate = null;

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            // Mengambil tanggal pengembalian dari tabel berdasarkan indeks kolom yang benar
            String Tglpengembalian = Tablepengembalian.getValueAt(Tablepengembalian.getSelectedRow(), 6).toString();
            TglpengembalianDate = sdf.parse(Tglpengembalian);

            // Mendapatkan tanggal keterlambatan dari JDateChooser
            tglKeterlambatanDate = dtelat.getDate();

            if (tglKeterlambatanDate == null) {
                JOptionPane.showMessageDialog(null, "Silakan pilih Tanggal Keterlambatan.");
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan dalam format tanggal.");
            return;
        }

        // Menghitung perbedaan hari
        long diffInMillies = tglKeterlambatanDate.getTime() - TglpengembalianDate.getTime();
        long diffInDays = diffInMillies / (1000 * 60 * 60 * 24);

        // Jika keterlambatan ada (lebih dari 0 hari), hitung denda
        if (diffInDays > 0) {
            int dendaKeterlambatan = (int) diffInDays * 2000;
            tdenda.setText(String.valueOf(dendaKeterlambatan));
        } else {
            // Jika tidak ada keterlambatan, denda nol
            tdenda.setText("0");
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void tdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdendaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dendaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dendaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dendaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dendaperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dendaperpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablepengembalian;
    private javax.swing.JButton btncari2;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnhitung2;
    private javax.swing.JButton btnhitung3;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JComboBox<String> ckategori2;
    private javax.swing.JComboBox<String> ckondisi;
    private javax.swing.JComboBox<String> ckondisi2;
    private javax.swing.JComboBox<String> cminjam1;
    private javax.swing.JComboBox<String> cminjam2;
    private com.toedter.calendar.JDateChooser dtelat;
    private com.toedter.calendar.JDateChooser dtelat2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jdataanggota;
    private javax.swing.JMenuItem jdatabuku;
    private javax.swing.JMenuItem jdatapegawai;
    private javax.swing.JMenuItem jdatapeminjaman;
    private javax.swing.JMenuItem jdatapengembalian;
    private javax.swing.JMenuItem jdenda;
    private javax.swing.JMenuItem jmenu;
    private javax.swing.JMenu jmenuanggota;
    private javax.swing.JMenu jmenubuku;
    private javax.swing.JMenu jmenudenda;
    private javax.swing.JMenu jmenupegawai;
    private javax.swing.JMenu jmenupeminjaman;
    private javax.swing.JMenu jmenupengembalian;
    private javax.swing.JMenu jmenuutama;
    private javax.swing.JTextField tcari2;
    private javax.swing.JTextField tdenda;
    private javax.swing.JTextField tdenda2;
    private javax.swing.JTextField tdenda3;
    // End of variables declaration//GEN-END:variables

}
