
package tugasperpus;
import java.io.File;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import java.util.HashMap;
import java.util.Locale;


import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.table.DefaultTableModel;
import static tugasperpus.koneksi.koneksiDb;
/**
 *
 * @author firzi
 */
public class Pegawaiperpus extends javax.swing.JFrame {
    Connection koneksi = null;
    private DefaultTableModel tabmode;
    
    /**
     * Creates new form Pegawaiperpus
     */
    public Pegawaiperpus() {
        initComponents();
        setLocationRelativeTo(null);
        koneksi = koneksiDb();
        datapegawai();
        Locale locale = new Locale ("id","ID");
       Locale.setDefault(locale);
        JComboBox<Object> comboBox = new JComboBox<>();
        comboBox.addItem("Nip");
        comboBox.addItem("Nama pegawai");
        
        rjk1.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (rjk1.isSelected()) {
            rjk2.setSelected(false);  // Reset pilihan Perempuan jika memilih Laki-laki
        }
    }
});

// Event untuk memilih Perempuan
rjk2.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (rjk2.isSelected()) {
            rjk1.setSelected(false);  // Reset pilihan Laki-laki jika memilih Perempuan
        }
    }
});
        
    }

    
     protected void aktif(){
        tnip.setEnabled(true);
        tpegawai.setEnabled(true);
        ttgl.setEnabled(true);
        talm.setEnabled(true);
        tnip.requestFocus();
     }
     
     protected void kosong () {
        tnip.setText("");
        tpegawai.setText("");
        ttgl.setText("");
        rjk1.setSelected(true);
        cagama.setSelectedIndex(0);
        cjabatan.setSelectedIndex(0);
        tnotlpn.setText("");
        talm.setText("");
        tcaripegawai.setText("");
        
    }
    
     protected void datapegawai () {
    Object[] Baris ={"Nip", "Nama_pegawai", "TTGL", "Jk", "Agama", "Jabatan", "Alamat", "No_telpon"};
    tabmode = new DefaultTableModel(null, Baris);
    Tablepegawai.setModel(tabmode);
    String sql = "SELECT * FROM db_pegawai";
    try {
        java.sql.Statement stat = koneksi.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
           String a = hasil.getString("Nip");
           String b = hasil.getString("Nama_pegawai");
           String c = hasil.getString("Ttgl");
           String d = hasil.getString("Jk");
           String e = hasil.getString("Agama");
           String f = hasil.getString("Jabatan");
           String g = hasil.getString("Alamat");
           String h = hasil.getString("No_telpon");
           
           String[] data={a,b,c,d,e,f,g,h};
           tabmode.addRow(data);
       }
       } catch (SQLException e) {
        System.out.println("Error Data:" + e.getMessage());
    }
}  
     
    private Connection koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_login","root","");
        return koneksi;
        
    }catch (Exception e){
        System.out.println("Koneksi Gagal:" + e.getMessage());
        return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tnip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tpegawai = new javax.swing.JTextField();
        ttgl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tnotlpn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        rjk1 = new javax.swing.JRadioButton();
        rjk2 = new javax.swing.JRadioButton();
        bntcari = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tcaripegawai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        cjabatan = new javax.swing.JComboBox<>();
        cpencarianpegawai = new javax.swing.JComboBox<>();
        cagama = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        talm = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablepegawai = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuback = new javax.swing.JMenu();
        jback = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenuback1 = new javax.swing.JMenu();
        mdatabuku = new javax.swing.JMenuItem();
        jmenuback2 = new javax.swing.JMenu();
        mdataanggota = new javax.swing.JMenuItem();
        jmenuback3 = new javax.swing.JMenu();
        mdataperpustakawan = new javax.swing.JMenuItem();
        jmenuback4 = new javax.swing.JMenu();
        mdatapeminjaman = new javax.swing.JMenuItem();
        jmenuback5 = new javax.swing.JMenu();
        mdatapengembalian = new javax.swing.JMenuItem();
        jmenuback6 = new javax.swing.JMenu();
        mdenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/Administrasii_Perpus.png")).getImage());
        setMinimumSize(new java.awt.Dimension(1076, 650));
        setPreferredSize(new java.awt.Dimension(1053, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("NIP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        getContentPane().add(tnip, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 121, 193, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("PEGAWAI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, -1, -1));
        getContentPane().add(tpegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 172, 193, -1));
        getContentPane().add(ttgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 223, 193, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("TTGL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("JK");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 274, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("JABATAN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 171, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("NO. TELPON");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 222, -1, -1));
        getContentPane().add(tnotlpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 223, 173, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("AGAMA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 120, -1, -1));

        rjk1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rjk1.setText("Laki-laki");
        getContentPane().add(rjk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 274, 78, -1));

        rjk2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rjk2.setText("Perempuan");
        getContentPane().add(rjk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 274, -1, -1));

        bntcari.setBackground(new java.awt.Color(255, 255, 51));
        bntcari.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        bntcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        bntcari.setText("CARI");
        bntcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntcariActionPerformed(evt);
            }
        });
        getContentPane().add(bntcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 272, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 204, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMINISTRASI PERPUSTAKAAN");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SDIT Hidayatullah");

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Jl. Cilangkap Baru No.99, RT.1/RW.1, Cilangkap, Kec. Cipayung, Kota Jakarta Timur");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Instagram : tkit_cahayabintang ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(180, 180, 180))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 520, 110));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_SD (1).png"))); // NOI18N
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA PUSTAKAWAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 570, 109));
        getContentPane().add(tcaripegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 275, 173, -1));

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));

        btnexit.setBackground(new java.awt.Color(255, 255, 51));
        btnexit.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitlogo.png"))); // NOI18N
        btnexit.setText("KELUAR");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(255, 255, 51));
        btnclear.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refreshlogo.png"))); // NOI18N
        btnclear.setText("REFRESH");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 255, 51));
        btndelete.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hapuslogo.png"))); // NOI18N
        btndelete.setText("HAPUS");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(255, 255, 51));
        btnedit.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editlogo.png"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnsave.setBackground(new java.awt.Color(255, 255, 51));
        btnsave.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simpanlogo.png"))); // NOI18N
        btnsave.setText("SIMPAN");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnprint.setBackground(new java.awt.Color(255, 255, 51));
        btnprint.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printerlogo.png"))); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        cjabatan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "STAF", "PUSTAKAWAN" }));

        cpencarianpegawai.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cpencarianpegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIP", "Pustakawan" }));

        cagama.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KRISTEN" }));

        talm.setColumns(20);
        talm.setRows(5);
        jScrollPane1.setViewportView(talm);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("ALAMAT");

        Tablepegawai.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        Tablepegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIP", "NAMA ", "TTL", "JK", "AGAMA", "JABATAN", "ALAMAT", "NO_TELPON"
            }
        ));
        Tablepegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablepegawaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tablepegawai);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnsave)
                        .addGap(23, 23, 23)
                        .addComponent(btnedit)
                        .addGap(21, 21, 21)
                        .addComponent(btndelete)
                        .addGap(19, 19, 19)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnexit)
                        .addGap(23, 23, 23)
                        .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(cpencarianpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addComponent(cjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(cpencarianpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsave)
                    .addComponent(btnedit)
                    .addComponent(btndelete)
                    .addComponent(btnclear)
                    .addComponent(btnexit)
                    .addComponent(btnprint))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1080, 520));

        jmenuback.setText("Menu Utama");
        jmenuback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenubackActionPerformed(evt);
            }
        });

        jback.setText("Menu Utama");
        jback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbackActionPerformed(evt);
            }
        });
        jmenuback.add(jback);

        jMenuBar1.add(jmenuback);
        jMenuBar1.add(jMenu2);

        jmenuback1.setText("Buku");
        jmenuback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuback1ActionPerformed(evt);
            }
        });

        mdatabuku.setText("Data Buku");
        mdatabuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatabukuActionPerformed(evt);
            }
        });
        jmenuback1.add(mdatabuku);

        jMenuBar1.add(jmenuback1);

        jmenuback2.setText("Anggota");
        jmenuback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuback2ActionPerformed(evt);
            }
        });

        mdataanggota.setText("Data Anggota");
        mdataanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdataanggotaActionPerformed(evt);
            }
        });
        jmenuback2.add(mdataanggota);

        jMenuBar1.add(jmenuback2);

        jmenuback3.setText("Pustakawan");
        jmenuback3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuback3ActionPerformed(evt);
            }
        });

        mdataperpustakawan.setText("Data Pustakawan");
        mdataperpustakawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdataperpustakawanActionPerformed(evt);
            }
        });
        jmenuback3.add(mdataperpustakawan);

        jMenuBar1.add(jmenuback3);

        jmenuback4.setText("Peminjaman");
        jmenuback4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuback4ActionPerformed(evt);
            }
        });

        mdatapeminjaman.setText("Data Peminjaman");
        mdatapeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatapeminjamanActionPerformed(evt);
            }
        });
        jmenuback4.add(mdatapeminjaman);

        jMenuBar1.add(jmenuback4);

        jmenuback5.setText("Pengembalian");
        jmenuback5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuback5ActionPerformed(evt);
            }
        });

        mdatapengembalian.setText("Data Pengembalian");
        mdatapengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdatapengembalianActionPerformed(evt);
            }
        });
        jmenuback5.add(mdatapengembalian);

        jMenuBar1.add(jmenuback5);

        jmenuback6.setText("Denda");
        jmenuback6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuback6ActionPerformed(evt);
            }
        });

        mdenda.setText("Denda");
        mdenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdendaActionPerformed(evt);
            }
        });
        jmenuback6.add(mdenda);

        jMenuBar1.add(jmenuback6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO db_pegawai (Nip, Nama_pegawai, Ttgl, Jk, Agama, Jabatan, Alamat, No_telpon) VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement ps = koneksi.prepareStatement(sql);
            ps.setString(1, tnip.getText());
            ps.setString(2, tpegawai.getText());
            ps.setString(3, ttgl.getText());
            
            String jkel="";
            if(rjk1.isSelected()) jkel="Laki-laki";
            else jkel="Perempuan";
            ps.setString(4, jkel);
           
            ps.setString(5, cagama.getSelectedItem().toString());
            ps.setString(6, cjabatan.getSelectedItem().toString());
            ps.setString(7, talm.getText());
            ps.setString(8, tnotlpn.getText());
            
            ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil di Simpan");
                kosong();
                tnip.requestFocus();
                datapegawai();
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error:" + e.getMessage());
            }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void TablepegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablepegawaiMouseClicked
        // TODO add your handling code here:
         int bar = Tablepegawai.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        
        tnip.setText(a);
        tpegawai.setText(b);
        ttgl.setText(c);
        
        if(d.equals("Laki-laki")) {rjk1.setSelected(true); rjk2.setSelected(false);}
        else {rjk1.setSelected(false); rjk2.setSelected(true);}
        
        cagama.setSelectedItem(e);
        cjabatan.setSelectedItem(f);
        tnotlpn.setText(h);    
        talm.setText(g);
    }//GEN-LAST:event_TablepegawaiMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        int rowIndex = Tablepegawai.getSelectedRow();
       
       if (rowIndex == -1){
           JOptionPane.showMessageDialog(null, "Pilih data yang akan di ubah");
          return;
       } 
        
        try {
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_login","root","");
           String nip = tnip.getText();
           String nama = tpegawai.getText();
           String tempattanggallahir = ttgl.getText();
           String jeniskelamin = rjk1.isSelected() ? "Laki-laki" : "Perempuan";
           String agama = (String) cagama.getSelectedItem();
           String jabatan = (String) cjabatan.getSelectedItem();
           String alamat = talm.getText();
           String notelpon = tnotlpn.getText();
           
         
           String sql = "UPDATE db_pegawai SET Nip=?, Nama_pegawai=?, Ttgl=?, Jk=?, Agama=?, Jabatan=?, Alamat=?, No_telpon=?   WHERE Nip =?";
           PreparedStatement stat = koneksi.prepareStatement(sql);
           stat.setString(1, nip);
           stat.setString(2, nama);
           stat.setString(3, tempattanggallahir);
           stat.setString(4, jeniskelamin);
           stat.setString(5, agama);
           stat.setString(6, jabatan);
           stat.setString(7, alamat);
           stat.setString(8, notelpon);
           stat.setString(9, tabmode.getValueAt(rowIndex, 0).toString());
            
           
           int result = stat.executeUpdate();
           
            if(result == 1){
                
                JOptionPane.showMessageDialog(null, "Data berhasil diubah");
                kosong();
                tnip.requestFocus();
                datapegawai();
             } else {
                JOptionPane.showMessageDialog(null, "Gagal Mengubah");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
       }
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         int[] selectedRows = Tablepegawai.getSelectedRows();

    if (selectedRows.length == 0) {
        JOptionPane.showMessageDialog(null, "Pilih Data yang akan di Hapus");
        return;
    }

    // Buat koneksi dan statement di luar loop
    try {
        String sql = "DELETE FROM db_pegawai WHERE Nip=?";
        PreparedStatement stat = koneksi.prepareStatement(sql);

        // Loop untuk menghapus semua data yang dipilih
        for (int i = 0; i < selectedRows.length; i++) {
            int rowIndex = selectedRows[i];
            String nip = tabmode.getValueAt(rowIndex, 0).toString();
            stat.setString(1, nip);

            // Eksekusi perintah untuk menghapus data
            stat.executeUpdate();
        }

        // Setelah semua baris dihapus, tampilkan pesan sekali saja
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

        // Perbarui tampilan tabel setelah penghapusan
        datapegawai();
        kosong();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        kosong();
        datapegawai();
    }//GEN-LAST:event_btnclearActionPerformed

    private void bntcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntcariActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) cpencarianpegawai.getSelectedItem();
        String caripegawai = tcaripegawai.getText();
        
        
        
        Object[] Baris = {"Nip", "Nama", "Ttgl", "Jk", "Agama", "Jabatan", "Alamat", "No_telpon"};
        tabmode = new DefaultTableModel(null, Baris);
        Tablepegawai.setModel(tabmode);
        
        String sql = "SELECT * FROM db_pegawai WHERE Nip LIKE ? OR Nama_pegawai LIKE ?";
       
        try {
            PreparedStatement stat = koneksi.prepareStatement(sql);
            stat.setString(1, "%" + caripegawai + "%");
            stat.setString(2, "%" + caripegawai + "%");
            
            
            
            ResultSet hasil = stat.executeQuery();
            while(hasil.next()){
                String a = hasil.getString("Nip");
                String b = hasil.getString("Nama_pegawai");
                String c = hasil.getString("Ttgl");
                String d = hasil.getString("Jk");
                String e = hasil.getString("Agama");
                String f = hasil.getString("Jabatan");
                String g = hasil.getString("Alamat");
                String h = hasil.getString("No_telpon");
                
                String[] data={a, b, c, d, e, f, g, h};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erorr : " + e.getMessage());
        }
    }//GEN-LAST:event_bntcariActionPerformed

    private void jmenubackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenubackActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jmenubackActionPerformed

    private void jbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbackActionPerformed
        // TODO add your handling code here:
         dispose();

        MenuUtama MenuUtama= new MenuUtama();
        MenuUtama.setVisible(true);
    }//GEN-LAST:event_jbackActionPerformed

    private void mdatabukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatabukuActionPerformed
        // TODO add your handling code here:
         dispose();
        
        Bukuperpus Bukuperpus= new Bukuperpus();
        Bukuperpus.setVisible(true);
    }//GEN-LAST:event_mdatabukuActionPerformed

    private void jmenuback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuback1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuback1ActionPerformed

    private void mdataanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdataanggotaActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Anggotaperpus Anggotaperpus= new Anggotaperpus();
        Anggotaperpus.setVisible(true);
    }//GEN-LAST:event_mdataanggotaActionPerformed

    private void jmenuback2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuback2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuback2ActionPerformed

    private void mdataperpustakawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdataperpustakawanActionPerformed
        // TODO add your handling code here:
        dispose();
        
        Pegawaiperpus Pegawaiperpus= new Pegawaiperpus();
        Pegawaiperpus.setVisible(true);
    }//GEN-LAST:event_mdataperpustakawanActionPerformed

    private void jmenuback3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuback3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuback3ActionPerformed

    private void mdatapeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatapeminjamanActionPerformed
        // TODO add your handling code here:
         dispose();
        
        Peminjamanperpus Peminjamanperpus= new Peminjamanperpus();
        Peminjamanperpus.setVisible(true);
    }//GEN-LAST:event_mdatapeminjamanActionPerformed

    private void jmenuback4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuback4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuback4ActionPerformed

    private void mdatapengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdatapengembalianActionPerformed
        // TODO add your handling code here:
         dispose();
        
        Pengembalianperpus Pengembalianperpus= new Pengembalianperpus();
        Pengembalianperpus.setVisible(true);
    }//GEN-LAST:event_mdatapengembalianActionPerformed

    private void jmenuback5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuback5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuback5ActionPerformed

    private void mdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdendaActionPerformed
        // TODO add your handling code here:
          dispose();
        
        Dendaperpus Dendaperpus= new Dendaperpus();
        Dendaperpus.setVisible(true);
    }//GEN-LAST:event_mdendaActionPerformed

    private void jmenuback6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuback6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenuback6ActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        try {
        String namaFile = "src/Laporan/LaporanPegawai.jasper";
        Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_login","root",""); 
        HashMap<String, Object> parameter = new HashMap<>();
        File report_file = new File(namaFile);
        if (report_file.exists()) {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } else {
            JOptionPane.showMessageDialog(null, "File laporan tidak ditemukan.");
        }
    } catch (JRException e) {
        JOptionPane.showMessageDialog(null, "Error loading report: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
     }   
    }//GEN-LAST:event_btnprintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawaiperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawaiperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawaiperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawaiperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pegawaiperpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablepegawai;
    private javax.swing.JButton bntcari;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cagama;
    private javax.swing.JComboBox<String> cjabatan;
    private javax.swing.JComboBox<String> cpencarianpegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem jback;
    private javax.swing.JMenu jmenuback;
    private javax.swing.JMenu jmenuback1;
    private javax.swing.JMenu jmenuback2;
    private javax.swing.JMenu jmenuback3;
    private javax.swing.JMenu jmenuback4;
    private javax.swing.JMenu jmenuback5;
    private javax.swing.JMenu jmenuback6;
    private javax.swing.JMenuItem mdataanggota;
    private javax.swing.JMenuItem mdatabuku;
    private javax.swing.JMenuItem mdatapeminjaman;
    private javax.swing.JMenuItem mdatapengembalian;
    private javax.swing.JMenuItem mdataperpustakawan;
    private javax.swing.JMenuItem mdenda;
    private javax.swing.JRadioButton rjk1;
    private javax.swing.JRadioButton rjk2;
    private javax.swing.JTextArea talm;
    private javax.swing.JTextField tcaripegawai;
    private javax.swing.JTextField tnip;
    private javax.swing.JTextField tnotlpn;
    private javax.swing.JTextField tpegawai;
    private javax.swing.JTextField ttgl;
    // End of variables declaration//GEN-END:variables
}
