/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasperpus;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.ImageIcon;

/**
 *
 * @author firzi
 */
public class Registerperpus extends javax.swing.JFrame {

    private boolean isPasswordVisible;

    /**
     * Creates new Registerperpus
     */
    public Registerperpus(){
        initComponents();
        setLocationRelativeTo(null);
    
         tuserr.setText("Username");
    tuserr.setForeground(new java.awt.Color(153, 153, 153));
    tuserr.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (tuserr.getText().equals("Username")) {
                tuserr.setText("");
                tuserr.setForeground(new java.awt.Color(0, 0, 0));
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (tuserr.getText().isEmpty()) {
                tuserr.setText("Username");
                tuserr.setForeground(new java.awt.Color(153, 153, 153));
            }
        }
    });

    // Placeholder untuk password (tpass)
    tpasss.setText("Password");
    tpasss.setEchoChar((char) 0); // Tampilkan teks biasa
    tpasss.setForeground(new java.awt.Color(153, 153, 153));
    tpasss.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (new String(tpasss.getPassword()).equals("Password")) {
                tpasss.setText("");
                tpasss.setForeground(new java.awt.Color(0, 0, 0));
                tpasss.setEchoChar('•'); // Ganti dengan karakter password
            }
        }

        @Override
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (new String(tpasss.getPassword()).isEmpty()) {
                tpasss.setText("Password");
                tpasss.setForeground(new java.awt.Color(153, 153, 153));
                tpasss.setEchoChar((char) 0); // Tampilkan teks biasa
            }
        }
    });

    // Fokus awal ke tombol Login
    btndaftar.requestFocus();
}
        
    public void cek_login()
    {
        Connection kon=koneksi.koneksiDb();
        try
        {
            Statement st=kon.createStatement();
            String sql="SELECT * FROM registerperpus WHERE username='" + tuserr.getText()+"' and password='"+tpasss.getText()+"'";
            ResultSet rs=st.executeQuery(sql);
            
            if(rs.next()) {
              JOptionPane.showMessageDialog(null, "Selamat Datang ");
                formlogin formlogin= new formlogin();
                formlogin.setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Login Gagal");
                tuserr.setText("");
                tpasss.setText("");
                tuserr.requestFocus();
            }
            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void register() {
        Connection kon = koneksi.koneksiDb();
        try {
            Statement st = kon.createStatement();
            String sql = "INSERT INTO loginperpus (username, password) VALUES ('" +tuserr.getText()+"', '" +tpasss.getText()+"')";
            int result = st.executeUpdate(sql);
            
            if(result > 0) {
                JOptionPane.showMessageDialog(null, "Registrasi Berhasil");
                formlogin formlogin= new formlogin();
                formlogin.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Registrasi  Gagal");
                 tuserr.setText("Username");
            tuserr.setForeground(new java.awt.Color(153, 153, 153));
            
            // Reset placeholder untuk password
            tpasss.setText("Password");
            tpasss.setForeground(new java.awt.Color(153, 153, 153));
            tpasss.setEchoChar((char) 0); // Tampilkan teks biasa
            
            tuserr.requestFocus(); // Kembalikan fokus ke username
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tuserr = new javax.swing.JTextField();
        tpasss = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btndaftar = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnmata = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/Administrasii_Perpus.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_SDIT1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 88, 84));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrasi Perpustakaan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 220, 20));
        getContentPane().add(tuserr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 250, 30));
        getContentPane().add(tpasss, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 250, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 42, 31));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 40, 30));

        btndaftar.setBackground(new java.awt.Color(102, 255, 102));
        btndaftar.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btndaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registration (1).png"))); // NOI18N
        btndaftar.setText("REGISTER");
        btndaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndaftarActionPerformed(evt);
            }
        });
        getContentPane().add(btndaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 250, -1));

        btnkembali.setBackground(new java.awt.Color(102, 255, 102));
        btnkembali.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undo (1).png"))); // NOI18N
        btnkembali.setText("KEMBALI");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 250, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnmata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye (2).png"))); // NOI18N
        btnmata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(btnmata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnmata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 370, 280));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sistem Administrasi Perpustakaan ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 390, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SDIT HIDAYATULLAH");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gembok2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 40, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("\"Dengan buku, kita menuntut ilmu yang menjulang tinggi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 400, 60));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("menginspirasi generasi, dan menerangi jalan bangsa.\"");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 400, 40));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("\" Ki Hajar Dewantara \"");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg sekolah.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndaftarActionPerformed
       // TODO add your handling code here:
        register();
    }//GEN-LAST:event_btndaftarActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
        formlogin formlogin= new formlogin();
        formlogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void btnmataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmataActionPerformed
        // TODO add your handling code here:
          if (isPasswordVisible) {
            tpasss.setEchoChar('•');  // Menyembunyikan password
            isPasswordVisible = false;
        } else {
            tpasss.setEchoChar((char) 0);  // Menampilkan password
            isPasswordVisible = true;
        }
    }//GEN-LAST:event_btnmataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registerperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registerperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registerperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registerperpus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registerperpus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndaftar;
    private javax.swing.JButton btnkembali;
    private javax.swing.JButton btnmata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField tpasss;
    private javax.swing.JTextField tuserr;
    // End of variables declaration//GEN-END:variables

    
}
